version: '3.7'
services: 
  db:
    image: bitnami/postgresql:13
    container_name: db
    ports: 
      - "5432:5432"
    volumes: 
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASS}
      - POSTGRESQL_DATABASE=${DB_NAME}
  minio:
    image: minio/minio
    container_name: ObjectStorageBucket
    ports: 
      - 9000:9000
    volumes:
      - data1:/data1
    environment: 
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server   http:://minio/data1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes: 
  postgresql_data:
    driver: local
  data1:
    driver: local